### ISSUE TITLE
Server with crashes (announcing restart)

### ISSUE THREAD

**Issue by danimesq** [Ecuacion/Lumen-Pokemon-Showdown#3]
Hi. I've cloned all commits of Lumen repository to my Pokémon Showdown
Server Template:
https://github.com/DaniellMesquita/Pokemon-Showdown-Server-Template
But, when install in server, this opens normal, but with a restart.
NOTE: I've not modified the code, then the possibility to the problem is the same of Lumen is high.
error. Can U reproduce the error and see if the problem is the same in
the Lumen repository?

**Comment by Ecuacion** [comment]
First of all, this repository is outdated. It was a server that ran in Openshift (free hosting of node 0.10.0). Since October / 2015, Lumen joined another servers and now its name is Big Bang and its code is managed by a private repository. In consequence, I stopped maintaining this repository.

Other problem is that Pokemon Showdown now requires Node > 4.0.0, so is no longer compatible with Openshift hosting.

I recommend you these servers repositories if you want to make your own one:
- https://github.com/Zarel/Pokemon-Showdown (Main)
- https://github.com/CreaturePhil/Showdown-Boilerplate (Good Template)
- https://github.com/panpawn/Pokemon-Showdown
